---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: laravel-app
    namespace: dad-group-9
spec:
    replicas: 1
    selector:
        matchLabels:
            app: laravel-app
    template:
        metadata:
            labels:
                app: laravel-app
        spec:
            containers:
                - name: api
                  image: registry.172.22.21.107.sslip.io/dad-group-9/api:v1.0.10
---
apiVersion: v1
kind: Service
metadata:
    name: laravel-app
    namespace: dad-group-9
spec:
    ports:
        - port: 80
    selector:
        app: laravel-app
